config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  # Routes for registration and session
  devise_for :users, controllers: { registrations: 'registrations' }

  # Root
  root to: 'application#home'

  # Public routes
  scope '/public' do
    get '/home', to: 'application#home', as: 'home'
    get '/about', to: 'application#about', as: 'about'
    get '/contact', to: 'application#contact', as: 'contact'
  end

  # Authorized routes
  resources :groups, only: [:index, :new, :create, :show]

  get '/add_member/:id', to: 'groups#add_member', as: 'add_member'
  post '/group/:id/save_member', to: 'groups#save_member', as: 'save_member'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :groups
  has_many :transactions

  def full_name
    [self.first_name, self.last_name].compact.join(' ')
  end

  def group_expenses(group_id)
    expenses = self.transactions.where(group_id: group_id)
    group_expenses = expenses.sum(&:amount)
    amount_paid = expenses.sum(&:amount_paid)

    net_amount = group_expenses - amount_paid

    "#{net_amount > 0 ? 'owed' : 'overpaid'} #{net_amount.abs}"
  rescue
    ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
  end

  def about
  end

  def contact
  end

  private

  def require_login
    unless current_user
      redirect_to new_user_session_url
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login

  def new
  end

  def index
    @groups = current_user.groups.includes(:transactions)
  end

  def create
    current_user.groups.build(group_params)
    current_user.save
    redirect_to groups_path
  end

  def show
    @group = current_user.groups.find(params[:id])
    @expenses = Transaction.where(group_id: params[:id]).sum(&:amount)
  end

  def add_member
    @group = current_user.groups.find(params[:id])
  end

  def save_member
    email = params[:member][:email]
    member = User.includes([:groups]).find_by_email(email)
    group_id = params[:id]

    unless member.nil?
      group = Group.find(group_id)
      member.groups << group if group && !member.groups.include?(group)

      redirect_to group_path(group_id)
    else
      redirect_to add_member_path(group_id), alert: "User with email id '#{email}' is not present."
    end
  rescue
    redirect_to add_member_path(group_id),  notice: 'Something went wrong. Please try again.'
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  CHECK_BOX_CHECKED_VALUE = '1'
  DEFAULT_TRANSACTION_VALUE = 0.0

  def index
    @transactions = Transaction.includes([:user, :group])
                               .where(group_id: params[:id])
  end

  def new
    @group = Group.find(params[:id])
  end

  def create
    group_id, member_list, date, total_amount = form_params
    split_in = split_in(member_list)

    if split_in.zero?
      redirect_to new_transaction_path(id: group_id), alert: 'Select at least one member.'
      return
    end

    memeber_share = total_amount / split_in

    user_transactions = []
    members = User.where(email: member_list.keys)
    members.each do |member|
      amount = member_list[member.email][:value].eql?(CHECK_BOX_CHECKED_VALUE) ?
               memeber_share : DEFAULT_TRANSACTION_VALUE
      amount_paid = member_list[member.email][:amount_paid].to_f

      user_transactions << {
        group_id: group_id,
        date: date,
        amount: amount,
        user_id: member.id,
        amount_paid: amount_paid
      }

      total_amount -= amount_paid
    end

    unless total_amount.zero?
      redirect_to new_transaction_path(id: group_id), alert: 'The amount paid by individual and total expense does not match.'
      return
    end

    Transaction.create(user_transactions)

    redirect_to group_path(group_id)
  rescue
    redirect_to group_path(params[:transaction][:group_id]), notice: 'Something went wrong. Please try again.'
  end

  private
  def split_in(member_list)
    members = 0
    member_list.each do |_, v|
      members += 1 if CHECK_BOX_CHECKED_VALUE.eql?(v[:value])
    end

    members
  end

  def form_params
    transaction_params = params[:transaction]
    group_id = transaction_params[:group_id]
    member_list = transaction_params[:member_list]
    date = [
      transaction_params['date(1i)'.to_sym],
      transaction_params['date(2i)'.to_sym],
      transaction_params['date(3i)'.to_sym]
    ].join('/')
    total_amount = transaction_params[:amount].to_f

    [group_id, member_list, date, total_amount]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/about.html.haml
%h2.text-left About
.row
  .panel.panel-default
    .panel-body
      %p.text-success application about page

app/views/application/contact.html.haml
%h2.text-left Contact
.row
  .panel.panel-default
    .panel-body
      %p.text-success Applications Contact details

app/views/application/home.html.haml
%h2.text-left Home
.row
  .panel.panel-default
    .panel-body
      %p.text-success Applications Home page

app/views/groups/add_member.html.haml
%h2.text-center Add member
.row
  .col-lg-offset-3.col-lg-6.col-md-offset-3.col-md-6.col-sm-offset-2.col-sm-8.col-xs-12
    .panel.panel-default
      .panel-body
        = form_for(:member, url: save_member_path(id: @group.id, email: :member)) do |f|
          .form-group
            = f.label :email
            %br/
            = f.text_field :email, autofocus: true, placeholder: "Member email", class: "form-control"
          .actions
            = f.submit "Add member", class: "btn btn-primary btn-block"

app/views/groups/index.html.haml
%h2.text-left My Groups
.row
  .panel.panel-default
    .panel-body
      %table.table.table-striped.groups-table
        %thead
          %tr
            %th #
            %th Title
            %th Description
            %th Total expense
        %tbody
          - @groups.each.with_index(1) do |group, row|
            %tr
              %th{:scope => "row"}= row
              %td= link_to(group.title, group_path(id: group.id))
              %td= group.description
              %td= group.transactions.sum(&:amount)

app/views/groups/new.html.haml
%h2.text-center Create Group
.row
  .col-lg-offset-3.col-lg-6.col-md-offset-3.col-md-6.col-sm-offset-2.col-sm-8.col-xs-12
    .panel.panel-default
      .panel-body
        = form_for(:group, url: url_for(controller: 'groups', action: 'create'), html: { class: "form-create-group" }) do |f|
          .form-group
            = f.label :title
            %br/
            = f.text_field :title, autofocus: true, placeholder: "Group title", class: "form-control"
          .form-group
            = f.label :description
            %br/
            = f.text_area :description, placeholder: "Group description", cols: 20, rows: 20, class: "form-control group-description"
          .actions
            = f.submit "Create Group", class: "btn btn-primary btn-block"

app/views/groups/show.html.haml
.row
  .pull-left
    %h2.text-left Group info
  .pull-right
    = link_to "Show transactions", transactions_path(id: @group.id), class: "btn btn-default"
    = link_to "Add transaction", new_transaction_path(id: @group.id), class: "btn btn-default"
    = link_to "Add member", add_member_path(@group.id), class: "btn btn-default"
.row
  .panel.panel-default
    .panel-body.group-info
      %table.table.groups-table
        %thead
          %tr
            %th Title
            %th.group-title{:colspan => "2"}= @group.title
          %tr
            %th Expenses
            %th.group-expenses{:colspan => "3"}= @expenses
        %tbody
          %tr
            %th description
            %th.group-description{:colspan => "3"}= @group.description
          - unless @group.users.empty?
            %tr
              %th #
              %th{:scope => "member-name-label"} Member name
              %th.member-email-label Member email
              %th.member-amount-owed-label Amount
            - @group.users.each.with_index(1) do |member, row|
              %tr
                %td{:scope => "row"}= row
                %td.member-name= member.full_name
                %td.member-email= member.email
                %td.member-amount= member.group_expenses(@group.id)

app/views/layouts/_navigation.html.haml
%ul.nav.navbar-nav
  %li= link_to('<span class="glyphicon glyphicon-home"></span> Split Wisely'.html_safe, root_path)
  - if current_user
    %li= link_to('<span class="glyphicon glyphicon-home"></span> My Groups'.html_safe, groups_path)
    %li= link_to('<span class="glyphicon glyphicon-lock"></span> Create Group'.html_safe, new_group_path)
  - else
    %li= link_to('<span class="glyphicon glyphicon-phone-alt"></span> Contact Us'.html_safe, contact_path)
    %li= link_to('<span class="glyphicon glyphicon-user"></span> About Us'.html_safe, about_path)
%ul.nav.navbar-nav.navbar-right
  - if current_user
    %li= link_to('<span class="glyphicon glyphicon-cog"></span> My Profile'.html_safe, edit_user_registration_path)
    %li= link_to('<span class="glyphicon glyphicon-off"></span> Log out'.html_safe, destroy_user_session_path, methods: 'delete')
  - else
    %li= link_to('<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path)
    %li= link_to('<span class="glyphicon glyphicon-saved"></span> Register'.html_safe, new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SplitWisely
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      %div
        = render 'layouts/navigation'
    %div{:class => "container #{controller.controller_name}"}
      .flash
        %p{:class => "notice#{' visible' if notice}"}= notice
        %p{:class => "alert#{' visible' if alert}"}= alert
      = yield

app/views/transactions/index.html.haml
%h2.text-left Transactions
.row
  .panel.panel-default
    .panel-body
      %table.table.groups-table
        %thead
          %tr
            %th
              %strong Group
            %th
              %strong User
            %th
              %strong Date
            %th
              %strong Amount
        %tbody
          - @transactions.each do |transaction|
            %tr
              %td.group-title= transaction.group.title
              %td.user-name= transaction.user.full_name
              %td.date= transaction.date
              %td.amount= transaction.amount

app/views/transactions/new.html.haml
%h2.text-center New Transaction
.row
  .col-lg-offset-3.col-lg-6.col-md-offset-3.col-md-6.col-sm-offset-2.col-sm-8.col-xs-12
    .panel.panel-default
      .panel-body
        = form_for(:transaction, url: url_for(controller: 'transactions', action: 'create')) do |f|
          .form-group
            = f.label :group
            %br/
            = f.text_field :group, readonly: true, class: "form-control", value: @group.title
            = f.text_field :group_id, hidden: true, value: @group.id
          .form-group
            = f.label :date
            %br/
            = f.date_select :date, :start_year => Date.current.year, :end_year => Date.current.year - 5, class: "form-control"
          .form-group
            = f.label :amount
            %br/
            = f.text_field :amount, placeholder: "123.34", class: "form-control"
          .form-group
            = f.label :member_list
            = f.fields_for :member_list do |ml|
              %table
                - @group.users.each do |user|
                  = ml.fields_for "#{user.email.to_sym}" do |me|
                    %tr
                      %td= me.check_box('value')
                      %td= me.label(user.full_name)
                      %td= me.text_field :amount_paid, placeholder: "123.34", class: "form-control"
          .actions
            = f.submit "Save transaction", class: "btn btn-primary btn-block"
            = link_to 'Back', group_path(@group.id)